name: RV1109-RV1126 Firmware Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
  
    - name: Checkout
      uses: actions/checkout@v2
    - name: prepare
      run: |
        mkdir -p /opt/linux/
        cd /opt/linux/
        wget https://github.com/t3rm1n4l/megacmd/releases/download/0.016/megacmd_0.016_linux_amd64.zip
        unzip megacmd_0.016_linux_amd64.zip
        find
        sudo cp megacmd /usr/sbin/
        sudo chmod 777 /usr/sbin/megacmd
        
        echo { >> $HOME/.megacmd.json
        echo \"User\" : \"coderwuqiang@gmail.com\", >> $HOME/.megacmd.json
        echo \"Password\" : \"91459775\", >> $HOME/.megacmd.json
        echo \"DownloadWorkers\" : 4, >> $HOME/.megacmd.json
        echo \"UploadWorkers\" : 4, >> $HOME/.megacmd.json
        echo \"SkipSameSize\" : true, >> $HOME/.megacmd.json
        echo \"Verbose\" : 1 >> $HOME/.megacmd.json
        echo } >> $HOME/.megacmd.json
        
        echo "###########################"
        cat $HOME/.megacmd.json
        echo "###########################"
      shell: bash
      
    - name: Cache Primes
      id: cache-primes  
      uses: actions/cache@v2
      with:
        path: /opt/linux/
        key: ${{ runner.os }}-primes
        
    - name: action-megacmd
      run: |
        megacmd get https://mega.nz/file/qyhWgALb#fkIdvxDJpRmQDiCDhqsB93k6GwHQwh6SStl_yAqmXo8 /opt/linux/
    
    - name: copyfiles
      run: |
        docker images
        docker ps
        ls /opt/linux/
    
    - name: decompress-sdk
      run: |
        find / -name "*rk356**"
        cd /opt/linux/
        ls
        tar zxvf rk356x_sdk_v1.1.2_20210720.tar.gz
        /opt/linux/rk356x*
        ./build.sh
        
        shell: bash
        
        
