name: RV1109-RV1126 Firmware Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache Primes
      id: cache-primes  
      uses: actions/cache@v2
      with:
        path: /opt/linux/
        key: ${{ runner.os }}-primes

    - name: sysprepare
      run: |
        mkdir -p /opt/linux/
        cd /opt/linux/

    - name: download-megacmd
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        ls /opt/linux/
        curl https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd-Debian_10.0_amd64.deb --output megacmd.deb
    
    - name: prepare-megacmd
      run: |
        mkdir -p /opt/linux/
        cd /opt/linux/

        sudo apt-get update && sudo apt-get install curl gnupg2 -y && \
        curl https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd-Debian_10.0_amd64.deb --output megacmd.deb && \
        sudo apt install ./megacmd.deb -y && \
        sudo apt-get remove -y curl && \
        sudo apt-get clean
        
      shell: bash
        
    - name: download-sdk
      run: |
        mega-get https://mega.nz/file/W250FJBQ#c6vqQl0MfOSAosTRlCOiahgGqE8GOLQ5fyL6BzcXrbM /opt/linux/
    
    - name: copyfiles
      run: |
        ls /opt/linux/
    
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: rk356x_sdk_v1.1.2_20210720.tar.gz
        path: /opt/linux/rk356x_sdk_v1.1.2_20210720.tar.gz
    
    - name: decompress-sdk
      run: |
        cd /opt/linux/
        ls
        tar zxf RV1126_RV1109_SDK_2.2.1.tar.gz
        
    - name: building
      run: |
        cd /opt/linux/RV1126_RV1109_SDK_2.2.1/
        ./build.sh lunch
        expect "Which would you like?"
        exp_send "BoardConfig.mk\r"
        interact
        source envsetup.sh
        expect "Which would you like?"
        exp_send "rockchip_rv1126_rv1109\r"
        interact
        ./build.sh 

    - name: backup
      uses: actions/upload-artifact@v2
      with:
        name: megacmd.deb
        path: /opt/linux/RV1126_RV1109_SDK_2.2.1/IMAGE
        
