name: RV1109-RV1126 Firmware Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
  
    - uses: actions/checkout@v2

    - name: Cache Primes
      id: cache-primes  
      uses: actions/cache@v2
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: /generate-primes.sh -d prime-numbers

    - name: Use Prime Numbers
      run: /primes.sh -d prime-numbers
    
    - name: action-megacmd
      # You may pin to the exact commit or the version.
      # uses: Difegue/action-megacmd@043c6d2a167af3ae0904fc88c6b2829e4140dc8d
      uses: Difegue/action-megacmd@1.2.0
      with:
        args: get https://mega.nz/file/W250FJBQ#c6vqQl0MfOSAosTRlCOiahgGqE8GOLQ5fyL6BzcXrbM /opt/

