name: RV1109-RV1126 Firmware Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cache Primes
      id: cache-primes  
      uses: actions/cache@v2
      with:
        path: /opt/sdk/
        key: ${{ runner.os }}-primes

    - name: sysprepare
      run: |
        mkdir -p /opt/sdk/
        cd /opt/sdk/
        ls

    - name: download-megacmd
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        cd /opt/sdk/
        curl https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd-Debian_10.0_amd64.deb --output megacmd.deb
    
    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v2.15.0
      with:
        workflow: cmake.yml
        name: RV1126_RV1109_SDK_2.2.2.tar.xz
        path: /opt/sdk/RV1126_RV1109_SDK_2.2.2.tar.xz
    
    - name: prepare-megacmd
      run: |
        mkdir -p /opt/sdk/
        cd /opt/sdk/

        sudo apt-get update && sudo apt-get install curl gnupg2 -y && \
        curl https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd-Debian_10.0_amd64.deb --output megacmd.deb && \
        sudo apt install ./megacmd.deb -y && \
        sudo apt-get remove -y curl && \
        sudo apt-get clean
        
    - name: download-sdk
      run: |
        if [ ! -f "/opt/sdk/RV1126_RV1109_SDK_2.2.2.tar.xz" ]; then
          echo "can't find SDK download now!"
          mega-get https://mega.nz/file/b2hkCQSI#gwlIQJSuTsMR_hSwor7BjwXOPq603_HdeBl6M_MHeIo /opt/sdk/
        fi
    
    - name: copyfiles
      run: |
        ls /opt/sdk/
    
    - name: decompress-sdk
      run: |
        cd /opt/linux/
        ls
        tar Jxf RV1126_RV1109_SDK_2.2.2.tar.xz
        
    - name: building
      run: |
        cd /opt/linux/RV1126_RV1109_SDK_2.2.2/
        ./build.sh lunch
        expect "Which would you like?"
        exp_send "BoardConfig.mk\r"
        interact
        source envsetup.sh
        expect "Which would you like?"
        exp_send "rockchip_rv1126_rv1109\r"
        interact
        ./build.sh 

    - name: backup
      uses: actions/upload-artifact@v2
      with:
        name: megacmd.deb
        path: /opt/linux/RV1126_RV1109_SDK_2.2.2/IMAGE
        
