name: RV1109-RV1126 Firmware Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
  
    - name: Checkout
      uses: actions/checkout@v2
    - name: prepare
      run: |
        mkdir -p /opt/linux/
        cd /opt/linux/

        sudo apt-get update && sudo apt-get install curl gnupg2 -y && \
        curl https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd-Debian_10.0_amd64.deb --output megacmd.deb && \
        sudo apt install ./megacmd.deb -y && \
        sudo apt-get remove -y curl && \
        sudo apt-get clean
        
      shell: bash
      
    - name: Cache Primes
      id: cache-primes  
      uses: actions/cache@v2
      with:
        path: /opt/linux/
        key: ${{ runner.os }}-primes
        
    - name: action-megacmd
      run: |
        mega-get https://mega.nz/file/qyhWgALb#fkIdvxDJpRmQDiCDhqsB93k6GwHQwh6SStl_yAqmXo8 /opt/linux/
    
    - name: copyfiles
      run: |
        docker images
        docker ps
        ls /opt/linux/
    
    - name: decompress-sdk
      run: |
        find / -name "*rk356**"
        cd /opt/linux/
        ls
        tar zxvf rk356x_sdk_v1.1.2_20210720.tar.gz
        /opt/linux/rk356x*
        ./build.sh
        
        shell: bash
        
        
