name: RV1109-RV1126 Firmware Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
  
    - uses: actions/checkout@v2

    - name: Cache Primes
      id: cache-primes  
      uses: actions/cache@v2
      with:
        path: /opt/linux/
        key: ${{ runner.os }}-primes
        
    - name: prepare
      run: |
        sudo mkdir -p /opt/linux/
      shell: bash
      
    - name: action-megacmd
      # You may pin to the exact commit or the version.
      # uses: Difegue/action-megacmd@043c6d2a167af3ae0904fc88c6b2829e4140dc8d
      uses: Difegue/action-megacmd@1.2.0
      with:
        args: get https://mega.nz/file/W250FJBQ#c6vqQl0MfOSAosTRlCOiahgGqE8GOLQ5fyL6BzcXrbM /opt/linux/
    
    - name: decompress-sdk
      run: |
        find / -name "*rk356*.tar.gz*"
        cd /opt/linux/
        ls
        tar zxvf rk356x_sdk_v1.1.2_20210720.tar.gz
        /opt/linux/rk356x*
        ./build.sh
        
        shell: bash
        
        
