name: Self-hosted

on:
  watch:
    branches: [ main ]

jobs:
  build:

    runs-on: Linux

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: /opt/sdk/
        key: ${{ runner.os }}-primes

    - name: Cache Buildroot
      id: cache-buildroot
      uses: actions/cache@v2
      with:
        path: ~/.buildroot-ccache/
        key: ${{ runner.os }}-buildroot

    - name: sysprepare
      run: |
        mkdir -p /opt/sdk/
        cd /opt/sdk/
        ls

    - name: download-megacmd
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        cd /opt/sdk/
        curl https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd-Debian_10.0_amd64.deb --output megacmd.deb

    - name: prepare-buildroot
      uses: owlvisiontech/buildroot-prepare@main
